import type { Metadata } from "next";
import { Geist, Geist_Mono, Dongle, Moderustic } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./components/SessionWrapper";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const moderustic = Moderustic({
  subsets: ["latin"],
  variable: "--font-moderustic",
});

const dongle = Dongle({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-dongle",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${moderustic.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SessionWrapper>
          <Navbar />
       
          <main className="flex-1">
            {children}
          </main>

          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}